image: alpine

stages:
  - build
  - test

job1:
  stage: build
  tags:
    - test
  script:
    - composer --working-dir=project install
  artifacts:
    paths:
      - ./

job2:
  stage: test
  tags:
    - test
  script:
    - composer --working-dir=project test