image: alpine

stages:
  - build
  - test

build:
  stage: build
  tags:
    - test
  script:
    - composer --working-dir=project install
  artifacts:
    paths:
      - ./builds

test:
  stage: test
  tags:
    - test
  script:
    - composer --working-dir=project test